# Generated by Django 3.2.18 on 2023-02-26 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('base', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
            options={
                'db_table': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('mission', models.TextField(max_length=500)),
                ('manager', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'Departement',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('mission', models.TextField(max_length=500)),
                ('chef', models.CharField(max_length=70)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_hr.departement')),
            ],
            options={
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_hr.categorie')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_hr.service')),
            ],
            options={
                'db_table': 'Fonction',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('post_nom', models.CharField(max_length=70)),
                ('prenom', models.CharField(blank=True, max_length=70, null=True)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=10)),
                ('civil', models.CharField(choices=[('M', 'Marié'), ('C', 'Célibataire')], default='M', max_length=10)),
                ('naissance', models.DateField()),
                ('embauche', models.DateField()),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_hr.fonction')),
            ],
            options={
                'db_table': 'Agent',
            },
        ),
    ]
