# Generated by Django 3.2.18 on 2023-03-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data_hr', '0002_agent_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_hr.agent')),
            ],
            options={
                'db_table': 'Conge',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('post_nom', models.CharField(max_length=70)),
                ('prenom', models.CharField(blank=True, max_length=70, null=True)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], default='M', max_length=10)),
                ('statut', models.CharField(choices=[('E', 'Enfant'), ('EP', 'Epoux(se)'), ('A', 'Agent')], default='E', max_length=10)),
                ('naissance', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data_hr.agent')),
            ],
            options={
                'db_table': 'Charge',
            },
        ),
    ]
