# Generated by Django 3.2.18 on 2023-03-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_hr', '0003_auto_20230301_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='mission',
            field=models.CharField(max_length=200),
        ),
    ]
