# Generated by Django 3.2.18 on 2023-03-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_hr', '0004_alter_departement_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='mission',
            field=models.CharField(max_length=500),
        ),
    ]
