# Generated by Django 3.2.18 on 2023-03-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_hr', '0005_alter_service_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='embauche',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='naissance',
            field=models.DateField(blank=True),
        ),
    ]
