# Generated by Django 3.2.18 on 2023-03-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_hr', '0008_auto_20230307_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='embauche',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='naissance',
            field=models.DateTimeField(blank=True),
        ),
    ]
