# Generated by Django 3.2.18 on 2023-03-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_hr', '0011_alter_agent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='fichier/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
