# Generated by Django 3.2.18 on 2023-03-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_hr', '0012_auto_20230308_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='fichier',
        ),
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
