# Generated by Django 3.2.18 on 2023-03-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_hr', '0014_alter_agent_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='Actif',
            field=models.BooleanField(default=True),
        ),
    ]
