# Generated by Django 3.2.18 on 2023-03-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_hr', '0015_agent_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.FileField(blank=True, default='default-avatar.png', null=True, upload_to='photo/'),
        ),
    ]
