# Generated by Django 3.2.18 on 2023-03-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_hr', '0016_alter_agent_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
